[package]
name = "ror_launch"
version = "1.0.0"
authors = ["Sammy James <sammy.james@protonmail.com>"]

[dependencies]
log = "*"
simple_logger = "*"
curl = "*"
serde = "*"
serde_derive = "*"
serde-xml-rs = "*"
bytebuffer = "*"
sha2 = "*"
md-5 = "*"
base64 = "*"
tempfile = "*"